### ISSUE TITLE
Show US citizenship/residency in signature list?

### ISSUE THREAD

**Issue by madprime** [madprime/ChangeCLIA#8]

**Comment by gedankenstuecke** [comment]
I see the reasoning for this one (even though I'm not too happy about it, being one of the *others* 😜) Regardless of that I'm not sure whether it's a good idea to put it out for each user. People might not want their status be publicly disclosed next to their name? 

What about recording it as an (maybe optional) field and then displaying the aggregate in a plot? Like doing a stacked bar chart giving (60% Citizens, 30%  Residents, 10% Other?

**Comment by madprime** [comment]
Fair point. Aggregate states seems nicer (and could do those later).
